package fr.thomas_clement.utt;

public enum JestValue {
	
	HIGHTEST_HEARTS, HIGHTEST_DIAMONDS, HIGHTEST_CLUBS, HIGHTEST_SPADES, LOWEST_HEARTS, LOWEST_DIAMONDS, LOWEST_CLUBS, LOWEST_SPADES, MAJORITY_4, MAJORITY_3, MAJORITY_2, BEST_JEST, BEST_JEST_NOJOKER, JOKER, NONE;

}
